import { readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

const ENV_PATH = join(process.cwd(), ".env.local");

const ENV_KEYS = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "STRAVA_CLIENT_ID",
  "STRAVA_CLIENT_SECRET",
  "STRAVA_REDIRECT_URI",
  "NEXT_PUBLIC_APP_URL",
  "ADMIN_EMAILS",
] as const;

export type EnvKey = (typeof ENV_KEYS)[number];

function parseEnvFile(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    map.set(trimmed.slice(0, eq), trimmed.slice(eq + 1));
  }
  return map;
}

export function readEnvLocal(): Map<string, string> {
  if (!existsSync(ENV_PATH)) return new Map();
  return parseEnvFile(readFileSync(ENV_PATH, "utf-8"));
}

export function writeEnvLocal(updates: Partial<Record<EnvKey, string>>): void {
  const existing = readEnvLocal();

  for (const [key, value] of Object.entries(updates)) {
    if (value !== undefined && value !== "") {
      existing.set(key, value);
    }
  }

  const defaults: Record<string, string> = {
    STRAVA_REDIRECT_URI: "http://localhost:3000/api/strava/callback",
    NEXT_PUBLIC_APP_URL: "http://localhost:3000",
    ADMIN_EMAILS: "admin@katoennatie.com",
  };

  for (const [key, value] of Object.entries(defaults)) {
    if (!existing.has(key)) existing.set(key, value);
  }

  const lines = [
    "# Katoen Natie Moves Together — local environment",
    "# Generated by setup wizard",
    "",
    "# Supabase (required for registration)",
    `NEXT_PUBLIC_SUPABASE_URL=${existing.get("NEXT_PUBLIC_SUPABASE_URL") ?? ""}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${existing.get("NEXT_PUBLIC_SUPABASE_ANON_KEY") ?? ""}`,
    `SUPABASE_SERVICE_ROLE_KEY=${existing.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""}`,
    "",
    "# Strava OAuth (optional)",
    `STRAVA_CLIENT_ID=${existing.get("STRAVA_CLIENT_ID") ?? ""}`,
    `STRAVA_CLIENT_SECRET=${existing.get("STRAVA_CLIENT_SECRET") ?? ""}`,
    `STRAVA_REDIRECT_URI=${existing.get("STRAVA_REDIRECT_URI") ?? defaults.STRAVA_REDIRECT_URI}`,
    "",
    "# App",
    `NEXT_PUBLIC_APP_URL=${existing.get("NEXT_PUBLIC_APP_URL") ?? defaults.NEXT_PUBLIC_APP_URL}`,
    `ADMIN_EMAILS=${existing.get("ADMIN_EMAILS") ?? defaults.ADMIN_EMAILS}`,
    "",
  ];

  writeFileSync(ENV_PATH, lines.join("\n"), "utf-8");
}